ETISS 0.8.0: etiss::instr::OverlappedNode Class Reference
etiss::instr::OverlappedNode Class Reference
Public Member Functions
etiss_del_como (OverlappedNode) OverlappedNode(Instruction *matchInstr
Node m_delegateNode (delegateNode)
Instruction * resolve (BitArray &instr) override
performs a lookup for the matching Instruction for the passed instruction in the bit array.
std::string print (std::string indent, I pos, unsigned pfillwidth, bool printunused) override
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
Public Member Functions inherited from etiss::instr::Node
Node ()
ctor
virtual ~Node ()
dtor
virtual void compile (const std::map< const OPCode *, Instruction *, etiss::instr::less > &instrmap_, const BitArray &used, bool &ok, std::list< std::string > &warnings, std::list< std::string > &errors)
called by InstructionSet::compile() calls Node::compile() of sub nodes
virtual bool isInstruction ()
returns true if this object is an instance of etiss::instr::Instruction
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
Public Attributes
Node * delegateNode: m_matchInstr(matchInstr)
Instruction * m_matchInstr
Node * m_delegateNode
Detailed Description
Definition at line 530 of file Instruction.cpp.
Member Function Documentation
etiss_del_como()
etiss::instr::OverlappedNode::etiss_del_como (OverlappedNode)
m_delegateNode()
Node etiss::instr::OverlappedNode::m_delegateNode (delegateNode) inline
Definition at line 537 of file Instruction.cpp.
print()
std::string etiss::instr::OverlappedNode::print (std::string indent, I pos, unsigned pfillwidth, bool printunused) inline override virtual
recursive print function to produce a human readable text that represents the structure of this node and sub nodes
See also
InstructionSet::print()
Reimplemented from etiss::instr::Node.
Definition at line 552 of file Instruction.cpp.
References m_delegateNode, m_matchInstr, etiss::instr::Node::print(), and etiss::instr::Instruction::print().
resolve()
Instruction* etiss::instr::OverlappedNode::resolve (BitArray & instr) inline override virtual
performs a lookup for the matching Instruction for the passed instruction in the bit array.
Reimplemented from etiss::instr::Node.
Definition at line 541 of file Instruction.cpp.
References m_delegateNode, m_matchInstr, etiss::instr::Instruction::opc_, get_metrics::reader, and etiss::instr::Node::resolve().
Member Data Documentation
delegateNode
Node* etiss::instr::OverlappedNode::delegateNode
Definition at line 537 of file Instruction.cpp.
m_delegateNode
Node* etiss::instr::OverlappedNode::m_delegateNode
Definition at line 563 of file Instruction.cpp.
Referenced by etiss::instr::HandleCollision(), print(), and resolve().
m_matchInstr
Instruction* etiss::instr::OverlappedNode::m_matchInstr
Definition at line 562 of file Instruction.cpp.
Referenced by print(), and resolve().
The documentation for this class was generated from the following file:
/home/runner/work/etiss_test/etiss_test/src/Instruction.cpp