ETISS 0.8.0: RV32IMACFDArch Class Reference
RV32IMACFDArch Class Reference
#include <RV32IMACFDArch.h>
Public Member Functions
RV32IMACFDArch ()
virtual const std::set< std::string > & getListenerSupportedRegisters ()
virtual ETISS_CPU * newCPU ()
allocate new cpu structure
virtual void resetCPU (ETISS_CPU *cpu, etiss::uint64 *startpointer)
reset cpu (structure)
virtual void deleteCPU (ETISS_CPU *)
delete cpu structure
virtual std::shared_ptr< etiss::VirtualStruct > getVirtualStruct (ETISS_CPU *cpu)
get the VirtualStruct of the core to mitigate register access
virtual unsigned getMaximumInstructionSizeInBytes ()
virtual unsigned getInstructionSizeInBytes ()
virtual const std::set< std::string > & getHeaders () const
required headers (RV32IMACFD.h)
virtual etiss::int32 handleException (etiss::int32 code, ETISS_CPU *cpu)
This function will be called automatically in order to handling architecure dependent exceptions such as interrupt, system call, illegal instructions.
virtual void initInstrSet (etiss::instr::ModedInstructionSet &) const
This function is called during CPUArch initialization.
virtual void initCodeBlock (etiss::CodeBlock &cb) const
called before instructions are translated for the code block
virtual void compensateEndianess (ETISS_CPU *cpu, etiss::instr::BitArray &ba) const
Target architecture may have inconsistent endianess.
virtual etiss::InterruptVector * createInterruptVector (ETISS_CPU *cpu)
If interrupt handling is expected, vector table could be provided to support interrupt triggering.
virtual void deleteInterruptVector (etiss::InterruptVector *vec, ETISS_CPU *cpu)
delete an allocated interrupt vector object
virtual etiss::plugin::gdb::GDBCore & getGDBCore ()
get the GDBcore for RV32IMACFD architecture
Public Member Functions inherited from etiss::CPUArch
CPUArch (std::string archname)
virtual ~CPUArch ()
std::string getArchName () const
returns the name of this architecture.
std::string getName () const
returns the name of this architecture.
virtual unsigned getMaximumInstructionsPerMetaInstruction ()
maximum number of instructions in a meta instruction
virtual unsigned getSuperInstructionCount ()
fixed number of sub instructions per instruction (e.g.
virtual std::string getBlockGlobalCode ()
get c++ code snippet that is placed at the top of a translated block
virtual bool unlikelyInstruction (etiss::uint8 *instr, unsigned length, bool &ismetainstruction)
return true if the given data is unlikely to be an instruction.
virtual std::string getIncludePath ()
returns a path that will be used to look up header files
virtual void finalizeInstrSet (etiss::instr::ModedInstructionSet &) const
the default behavior of this function of a cpu arch is to add "cpu->cpuTime_ps += cpu->cpuCycleTime_ps;" if the cpu time update group is not in use
virtual etiss::mm::MMU * newMMU (ETISS_CPU *cpu)
It is an interface to instanciate a Memory Management Unit.
Public Member Functions inherited from etiss::CPUArchRegListenerInterface
virtual ~CPUArchRegListenerInterface ()
Public Member Functions inherited from etiss::CPUArchCPUManipulation
virtual ~CPUArchCPUManipulation ()
Public Member Functions inherited from etiss::CPUArchDefaultPlugins
virtual ~CPUArchDefaultPlugins ()
virtual etiss::Plugin * newTimer (ETISS_CPU *cpu)
create a simple default timer implementaion instance for this architecture.
virtual void deleteTimer (etiss::Plugin *timer)
delete timer instance
Public Member Functions inherited from etiss::TranslationPlugin
TranslationPlugin ()
virtual ~TranslationPlugin ()
virtual void finalizeCodeBlock (etiss::CodeBlock &) const
called after all instructions have been translated for the code block
virtual void * getPluginHandle ()
called to get the handle that is available in translated code via getPoinerCode(). [default: this]
Public Member Functions inherited from etiss::Plugin
virtual ~Plugin ()
unsigned getType ()
InterruptListenerPlugin * getInterruptListenerPlugin ()
CoroutinePlugin * getCoroutinePlugin ()
SystemWrapperPlugin * getSystemWrapperPlugin ()
RegisterDevicePlugin * getRegisterDevicePlugin ()
TranslationPlugin * getTranslationPlugin ()
std::string getPluginName () const
const std::string & getLastAssignedCoreName ()
std::string toString () const
Public Member Functions inherited from etiss::ToString
ToString ()
virtual ~ToString ()
Private Attributes
std::set< std::string > listenerSupportedRegisters_
std::set< std::string > headers_
RV32IMACFDGDBCore gdbcore_
Additional Inherited Members
Static Public Member Functions inherited from etiss::CPUArchRegListenerInterface
static void signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
call this function to inform RegisterDevicePlugins about changed special register values.
Static Public Attributes inherited from etiss::Plugin
static const unsigned INTERRUPTLISTENER = 1 << 0
access to translated code
static const unsigned COROUTINE = 1 << 1
callback after execution of each translated block
static const unsigned SYSTEMWRAPPER = 1 << 2
can wrap/change ETISS_System structure at execution start
static const unsigned REGISTERDEVICE
gets noticed of changes to special registers (e.g. mmu register etc. [depends on architecture])
static const unsigned TRANSLATION
access to translated code during translation phase or when instruction tree is built
Protected Member Functions inherited from etiss::CPUArch
virtual std::string _getPluginName () const
do not override. maps to getName().
Protected Member Functions inherited from etiss::TranslationPlugin
std::string getPointerCode () const
returns a C code expression that allows to get or assign a pointer to the variable assigned to this translation plugin.
Protected Member Functions inherited from etiss::Plugin
Plugin (unsigned type=0)
virtual void init (ETISS_CPU *cpu, ETISS_System *system, CPUArch *arch)
this function is called before the plugin is used in the cpu execution loop (etiss::CPUCore::execute).
virtual void cleanup ()
this function is called after cpu execution loop (etiss::CPUCore::execute) finished.
void setCorrespondingCPUCoreName (std::string name)
virtual void addedToCPUCore (etiss::CPUCore *core)
called as soon a plugin has been added to its CPUCore.
virtual void removedFromCPUCore (etiss::CPUCore *core)
called as soon a plugin has been removed from its CPUCore.
Protected Attributes inherited from etiss::Plugin
ETISS_CPU * plugin_cpu_
holds a pointer to the cpu structure. will be set before init call and after cleanup call
ETISS_System * plugin_system_
holds a pointer to the system structure.
CPUArch * plugin_arch_
holds a pointer to the CPUArch instance. will be set before init call and after cleanup call
CPUCore * plugin_core_
holds a pointer to the associated CPUCore instance.
Detailed Description
Definition at line 27 of file RV32IMACFDArch.h.
Constructor & Destructor Documentation
RV32IMACFDArch()
RV32IMACFDArch::RV32IMACFDArch ()
Definition at line 46 of file RV32IMACFDArch.cpp.
References headers_.
Member Function Documentation
compensateEndianess()
void RV32IMACFDArch::compensateEndianess (ETISS_CPU * cpu, etiss::instr::BitArray & ba) const virtual
Target architecture may have inconsistent endianess.
This function is called whenever a data is read from memory.
Data read from memory is buffered, and this function is called to alter sequence of buffered data so that the inconsistent endianess is compensated.
See also
RV32IMACFDArchSpecificImp.h
Target architecture may have inconsistent endianess. Data read from memory is buffered, and this function is called to alter sequence of buffered data so that the inconsistent endianess is compensated. Example for ARMv6M: void * ptr = ba.internalBuffer(); if (ba.byteCount() == 2) { ((uint32_t*)ptr) = ((uint16_t)(*((uint8_t*)ptr))) | ((uint16_t)(*(((uint8_t*)ptr)+1)) << 8); } else if (ba.byteCount() == 4) { ((uint32_t*)ptr) = ((((uint32_t)(*((uint8_t*)ptr))) | ((uint32_t)(*(((uint8_t*)ptr)+1)) << 8)) << 16) | ((uint32_t)(*(((uint8_t*)ptr)+2))) | ((uint32_t)(*(((uint8_t*)ptr)+3)) << 8); } else { etiss::log(etiss::FATALERROR,"Endianess cannot be handled",ba.byteCount()); }
Attention
Default endianess: little-endian
Reimplemented from etiss::CPUArch.
Definition at line 462 of file RV32IMACFDArchSpecificImp.cpp.
createInterruptVector()
etiss::InterruptVector * RV32IMACFDArch::createInterruptVector (ETISS_CPU * cpu) virtual
If interrupt handling is expected, vector table could be provided to support interrupt triggering.
See also
RV32IMACFDArchSpecificImp.h
Interrupt vector table is used to inform the core whenever an edge/level triggered interrupt incoming. The content of interrupt vector could be a special register or standalone interrupt lines.
Reimplemented from etiss::CPUArch.
Definition at line 493 of file RV32IMACFDArchSpecificImp.cpp.
deleteCPU()
void RV32IMACFDArch::deleteCPU (ETISS_CPU *) virtual
delete cpu structure
Implements etiss::CPUArch.
Definition at line 177 of file RV32IMACFDArch.cpp.
deleteInterruptVector()
void RV32IMACFDArch::deleteInterruptVector (etiss::InterruptVector * vec, ETISS_CPU * cpu) virtual
delete an allocated interrupt vector object
Reimplemented from etiss::CPUArch.
Definition at line 511 of file RV32IMACFDArchSpecificImp.cpp.
getGDBCore()
etiss::plugin::gdb::GDBCore & RV32IMACFDArch::getGDBCore () virtual
get the GDBcore for RV32IMACFD architecture
See also
RV32IMACFDGDBCore.h for implementation of GDBcore
Reimplemented from etiss::CPUArch.
Definition at line 213 of file RV32IMACFDArch.cpp.
References gdbcore_.
getHeaders()
const std::set< std::string > & RV32IMACFDArch::getHeaders () const virtual
required headers (RV32IMACFD.h)
Implements etiss::CPUArch.
Definition at line 201 of file RV32IMACFDArch.cpp.
References headers_.
getInstructionSizeInBytes()
unsigned RV32IMACFDArch::getInstructionSizeInBytes () virtual
Returns
2
Implements etiss::CPUArch.
Definition at line 193 of file RV32IMACFDArch.cpp.
getListenerSupportedRegisters()
const std::set< std::string > & RV32IMACFDArch::getListenerSupportedRegisters () virtual
See also
CPUArchRegListenerInterface::signalChangedRegisterValue
Implements etiss::CPUArchRegListenerInterface.
Definition at line 51 of file RV32IMACFDArch.cpp.
References listenerSupportedRegisters_.
getMaximumInstructionSizeInBytes()
unsigned RV32IMACFDArch::getMaximumInstructionSizeInBytes () virtual
Returns
8 (jump instruction + instruction of delay slot)
Implements etiss::CPUArch.
Definition at line 185 of file RV32IMACFDArch.cpp.
getVirtualStruct()
std::shared_ptr< etiss::VirtualStruct > RV32IMACFDArch::getVirtualStruct (ETISS_CPU * cpu) virtual
get the VirtualStruct of the core to mitigate register access
See also
RV32IMACFDArchSpecificImp.h
Implements etiss::CPUArchCPUManipulation.
Definition at line 469 of file RV32IMACFDArchSpecificImp.cpp.
References etiss::VirtualStruct::allocate().
handleException()
etiss::int32 RV32IMACFDArch::handleException (etiss::int32 cause, ETISS_CPU * cpu) virtual
This function will be called automatically in order to handling architecure dependent exceptions such as interrupt, system call, illegal instructions.
See also
RV32IMACFDArchSpecificImp.h
This file contains the architecture specific implementation for the RV32IMACFD core architecture.
WARNING: This file contains user-added code, be mindful when overwriting this with generated code!
This function will be called automatically in order to handling exceptions such as interrupt, system call, illegal instructions
Exception handling mechanism is implementation dependent for each cpu variant. Please add it to the following block if exception handling is demanded. Pesudo example: switch(cause){ case etiss::RETURNCODE::INTERRUPT: break;
Reimplemented from etiss::CPUArch.
Definition at line 30 of file RV32IMACFDArchSpecificImp.cpp.
References CAUSE_BREAKPOINT, CAUSE_FETCH_ACCESS, CAUSE_FETCH_PAGE_FAULT, CAUSE_ILLEGAL_INSTRUCTION, CAUSE_LOAD_ACCESS, CAUSE_LOAD_PAGE_FAULT, CAUSE_MACHINE_ECALL, CAUSE_STORE_ACCESS, CAUSE_STORE_PAGE_FAULT, CAUSE_SUPERVISOR_ECALL, CAUSE_USER_ECALL, etiss::cfg(), RV32IMACFD::CSR, CSR_MCAUSE, CSR_MEDELEG, CSR_MEPC, CSR_MIDELEG, CSR_MIE, CSR_MIP, CSR_MSTATUS, CSR_MTVAL, CSR_MTVEC, CSR_SCAUSE, CSR_SEPC, CSR_SSTATUS, CSR_STVEC, etiss::ERROR, etiss::INFO, ETISS_CPU::instructionPointer, likely, etiss::log(), MSTATUS_MIE, MSTATUS_MPIE, MSTATUS_MPP, MSTATUS_SIE, MSTATUS_SPP, MSTATUS_UIE, etiss::mm::NOERROR, PRV_M, PRV_S, PRV_U, unlikely, etiss::VERBOSE, and etiss::WARNING.
initCodeBlock()
void RV32IMACFDArch::initCodeBlock (etiss::CodeBlock &) const virtual
called before instructions are translated for the code block
Reimplemented from etiss::TranslationPlugin.
Definition at line 206 of file RV32IMACFDArch.cpp.
References etiss::CodeBlock::fileglobalCode(), and etiss::CodeBlock::functionglobalCode().
initInstrSet()
void RV32IMACFDArch::initInstrSet (etiss::instr::ModedInstructionSet & mis) const virtual
This function is called during CPUArch initialization.
See also
RV32IMACFDArchSpecificImp.h
Function pointer length_updater_ has to be replaced if multiple length instruction execution is supported. This function enables dynamic instruction length update in order to guarantee correct binary translation Pesudo example: vis->length_updater_ = [](VariableInstructionSet & ,InstructionContext & ic, BitArray & ba) { switch(ba.byteCount()){ case 4: if (INSTRUCTION_LENTH_NOT_EQUAL(4)){ updateInstrLength(ic, ba); ic.is_not_default_width_ = true; } break; } };
Reimplemented from etiss::TranslationPlugin.
Definition at line 309 of file RV32IMACFDArchSpecificImp.cpp.
References etiss::instr::InstructionCollection::addTo(), etiss::cfg(), etiss::instr::ModedInstructionSet::compile(), etiss::FATALERROR, etiss::Configuration::get(), etiss::instr::ModedInstructionSet::get(), if(), etiss::instr::InstructionContext::instr_width_, etiss::instr::InstructionContext::instr_width_fully_evaluated_, etiss::instr::InstructionContext::is_not_default_width_, etiss::instr::VariableInstructionSet::length_updater_, etiss::log(), etiss::instr::ModedInstructionSet::print(), etiss::instr::BitArrayRange::read(), RV32IMACFDISA, and etiss::Configuration::set().
newCPU()
ETISS_CPU * RV32IMACFDArch::newCPU () virtual
allocate new cpu structure
Implements etiss::CPUArch.
Definition at line 56 of file RV32IMACFDArch.cpp.
References resetCPU().
resetCPU()
void RV32IMACFDArch::resetCPU (ETISS_CPU * cpu, etiss::uint64 * startpointer) virtual
reset cpu (structure)
Implements etiss::CPUArch.
Definition at line 63 of file RV32IMACFDArch.cpp.
References RV32IMACFD::A0, RV32IMACFD::A1, RV32IMACFD::A2, RV32IMACFD::A3, RV32IMACFD::A4, RV32IMACFD::A5, RV32IMACFD::A6, RV32IMACFD::A7, ETISS_CPU::cpuCycleTime_ps, ETISS_CPU::cpuTime_ps, RV32IMACFD::CSR, RV32IMACFD::DPC, RV32IMACFD::F, RV32IMACFD::FCSR, RV32IMACFD::FENCE, RV32IMACFD::GP, RV32IMACFD::ins_CSR, RV32IMACFD::ins_X, ETISS_CPU::instructionPointer, memset(), ETISS_CPU::mode, RV32IMACFD::PRIV, RV32IMACFD::RA, RV32IMACFD::RES, RV32IMACFD::RES_ADDR, RV32IMACFD::S0, RV32IMACFD::S1, RV32IMACFD::S10, RV32IMACFD::S11, RV32IMACFD::S2, RV32IMACFD::S3, RV32IMACFD::S4, RV32IMACFD::S5, RV32IMACFD::S6, RV32IMACFD::S7, RV32IMACFD::S8, RV32IMACFD::S9, RV32IMACFD::SP, RV32IMACFD::T0, RV32IMACFD::T1, RV32IMACFD::T2, RV32IMACFD::T3, RV32IMACFD::T4, RV32IMACFD::T5, RV32IMACFD::T6, RV32IMACFD::TP, RV32IMACFD::X, and RV32IMACFD::ZERO.
Referenced by newCPU().
Member Data Documentation
gdbcore_
RV32IMACFDGDBCore RV32IMACFDArch::gdbcore_ private
Definition at line 103 of file RV32IMACFDArch.h.
Referenced by getGDBCore().
headers_
std::set<std::string> RV32IMACFDArch::headers_ private
Definition at line 102 of file RV32IMACFDArch.h.
Referenced by getHeaders(), and RV32IMACFDArch().
listenerSupportedRegisters_
std::set<std::string> RV32IMACFDArch::listenerSupportedRegisters_ private
Definition at line 101 of file RV32IMACFDArch.h.
Referenced by getListenerSupportedRegisters().
The documentation for this class was generated from the following files:
/home/runner/work/etiss_test/etiss_test/ArchImpl/RV32IMACFD/RV32IMACFDArch.h
/home/runner/work/etiss_test/etiss_test/ArchImpl/RV32IMACFD/RV32IMACFDArch.cpp
/home/runner/work/etiss_test/etiss_test/ArchImpl/RV32IMACFD/RV32IMACFDArchSpecificImp.cpp