ETISS 0.8.0: etiss::LibraryInterface Class Reference
etiss::LibraryInterface Class Reference
interface class for libraries.
#include <LibraryInterface.h>
Public Member Functions
LibraryInterface (std::string name)
virtual ~LibraryInterface ()
virtual std::string versionInfo ()
simple version info string. intended to present information in a human readable way.
virtual unsigned countPlugins ()
virtual unsigned countCPUArchs ()
virtual unsigned countJITs ()
virtual std::string nameJIT (unsigned index)
virtual std::string namePlugin (unsigned index)
virtual std::string nameCPUArch (unsigned index)
virtual etiss::JIT * createJIT (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::CPUArch * createCPUArch (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual etiss::Plugin * createPlugin (unsigned index, std::map< std::string, std::string > options=std::map< std::string, std::string >())
virtual void deleteJIT (etiss::JIT *)
virtual void deleteCPUArch (etiss::CPUArch *)
virtual void deletePlugin (etiss::Plugin *)
virtual bool isEmpty ()
returns true if this library provides nothing
virtual const std::string & getName ()
Static Public Member Functions
static std::shared_ptr< LibraryInterface > openSharedLibrary (std::string path, std::string name)
static std::shared_ptr< LibraryInterface > openIntegratedLibrary ()
static unsigned getCurrentLibraryVersion ()
static void addSearchPath (const std::string &path)
Private Attributes
std::string name_
Detailed Description
interface class for libraries.
override functions as needed.
it is neccessary to override all function of the same category. e.g. for plugins: countPlugins(),namePlugin(1),createPlugin(1),deletePlugin(1). isEmpty() uses countXXXXXX() functions to assess its return value and doesn't need to be implemented.
to implement a dynamic library do NOT use this class. Refer to etiss/helper/CPUArchLibrary.h , etiss/helper/JITLibrary.h , etiss/helper/PluginLibrary.h for library functions to implement and use etiss::LibraryInterface::openSharedLibrary to load the dynamic library
Definition at line 91 of file LibraryInterface.h.
Constructor & Destructor Documentation
LibraryInterface()
LibraryInterface::LibraryInterface (std::string name)
Parameters
name name of the library
path location of the library and its files
Definition at line 66 of file LibraryInterface.cpp.
~LibraryInterface()
LibraryInterface::~LibraryInterface () virtual
Definition at line 67 of file LibraryInterface.cpp.
Member Function Documentation
addSearchPath()
void LibraryInterface::addSearchPath (const std::string & path) static
Definition at line 606 of file LibraryInterface.cpp.
References int.
Referenced by TCCJIT::translate().
countCPUArchs()
unsigned LibraryInterface::countCPUArchs () virtual
Reimplemented in IntegratedLibrary.
Definition at line 78 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch(), and isEmpty().
countJITs()
unsigned LibraryInterface::countJITs () virtual
Reimplemented in IntegratedLibrary.
Definition at line 82 of file LibraryInterface.cpp.
Referenced by etiss::addLibrary(), etiss::getJIT(), and isEmpty().
countPlugins()
unsigned LibraryInterface::countPlugins () virtual
Reimplemented in IntegratedLibrary.
Definition at line 74 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin(), and isEmpty().
createCPUArch()
etiss::CPUArch * LibraryInterface::createCPUArch (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 104 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
createJIT()
etiss::JIT * LibraryInterface::createJIT (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 100 of file LibraryInterface.cpp.
Referenced by etiss::getJIT().
createPlugin()
etiss::Plugin * LibraryInterface::createPlugin (unsigned index, std::map< std::string, std::string > options = std::map<std::string, std::string>()) virtual
Reimplemented in IntegratedLibrary.
Definition at line 108 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
deleteCPUArch()
void LibraryInterface::deleteCPUArch (etiss::CPUArch *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 114 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
deleteJIT()
void LibraryInterface::deleteJIT (etiss::JIT *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 113 of file LibraryInterface.cpp.
Referenced by etiss::getJIT().
deletePlugin()
void LibraryInterface::deletePlugin (etiss::Plugin *) virtual
Reimplemented in IntegratedLibrary.
Definition at line 115 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
getCurrentLibraryVersion()
unsigned etiss::LibraryInterface::getCurrentLibraryVersion () static
Definition at line 152 of file IntegratedLibrary.cpp.
getName()
const std::string & LibraryInterface::getName () virtual
Returns
name of this library
Definition at line 122 of file LibraryInterface.cpp.
References name_.
Referenced by etiss::getCPUArch(), etiss::getJIT(), etiss::getPlugin(), and etiss::shutdown().
isEmpty()
bool LibraryInterface::isEmpty () virtual
returns true if this library provides nothing
Definition at line 117 of file LibraryInterface.cpp.
References countCPUArchs(), countJITs(), and countPlugins().
Referenced by etiss::getCPUArch(), etiss::getJIT(), and etiss::getPlugin().
nameCPUArch()
std::string LibraryInterface::nameCPUArch (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 95 of file LibraryInterface.cpp.
Referenced by etiss::getCPUArch().
nameJIT()
std::string LibraryInterface::nameJIT (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 87 of file LibraryInterface.cpp.
Referenced by etiss::addLibrary(), and etiss::getJIT().
namePlugin()
std::string LibraryInterface::namePlugin (unsigned index) virtual
Reimplemented in IntegratedLibrary.
Definition at line 91 of file LibraryInterface.cpp.
Referenced by etiss::getPlugin().
openIntegratedLibrary()
std::shared_ptr< etiss::LibraryInterface > etiss::LibraryInterface::openIntegratedLibrary () static
Definition at line 122 of file IntegratedLibraryHelper.cpp.
Referenced by etiss_initialize().
openSharedLibrary()
std::shared_ptr< LibraryInterface > LibraryInterface::openSharedLibrary (std::string path, std::string name) static
Definition at line 527 of file LibraryInterface.cpp.
References etiss::ERROR, ETISS_SRCLOC, ETISS_VARVAL, etiss::INFO, etiss::log(), name, etiss::VERBOSE, and etiss::WARNING.
Referenced by etiss::loadLibrary().
versionInfo()
std::string LibraryInterface::versionInfo () virtual
simple version info string. intended to present information in a human readable way.
Reimplemented in IntegratedLibrary.
Definition at line 69 of file LibraryInterface.cpp.
Member Data Documentation
name_
std::string etiss::LibraryInterface::name_ private
Definition at line 147 of file LibraryInterface.h.
Referenced by getName().
The documentation for this class was generated from the following files:
/home/runner/work/etiss_test/etiss_test/include/etiss/LibraryInterface.h
/home/runner/work/etiss_test/etiss_test/src/IntegratedLibrary.cpp
/home/runner/work/etiss_test/etiss_test/src/IntegratedLibraryHelper.cpp
/home/runner/work/etiss_test/etiss_test/src/LibraryInterface.cpp