ETISS 0.8.0: /home/runner/work/etiss_test/etiss_test/src/jitlibs/CSRCounters/CSRCounters.cpp File Reference
CSRCounters.cpp File Reference
#include <cstdint>
#include "etiss/CPUArch.h"
#include "etiss/jit/CPU.h"
#include "etiss/CPUCore.h"
#include "etiss/ETISS.h"
#include <chrono>
Functions
uint64 etiss_get_cycles (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers)
uint64 etiss_get_time ()
uint64 etiss_get_instret (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers)
Function Documentation
etiss_get_cycles()
uint64 etiss_get_cycles (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers) inline
Definition at line 13 of file CSRCounters.cpp.
References ETISS_CPU::cpuCycleTime_ps, and ETISS_CPU::cpuTime_ps.
Referenced by csr_read().
etiss_get_instret()
uint64 etiss_get_instret (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers) inline
Definition at line 26 of file CSRCounters.cpp.
References ETISS_CPU::cpuCycleTime_ps, and ETISS_CPU::cpuTime_ps.
Referenced by csr_read().
etiss_get_time()
uint64 etiss_get_time () inline
Definition at line 18 of file CSRCounters.cpp.
Referenced by csr_read().