ETISS 0.8.0: /home/runner/work/etiss_test/etiss_test/ArchImpl/RV32IMACFD/RV32IMACFDFuncs.h File Reference
RV32IMACFDFuncs.h File Reference
#include "Arch/RV32IMACFD/RV32IMACFD.h"
#include "etiss/jit/CPU.h"
#include "etiss/jit/System.h"
#include "etiss/jit/ReturnCode.h"
Functions
static void raise (etiss_int32 irq, etiss_int32 mcause)
static void leave (etiss_int32 priv_lvl)
static void wait (etiss_int32 flag)
static etiss_uint32 fadd_s (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fsub_s (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fmul_s (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fdiv_s (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fmadd_s (etiss_uint32, etiss_uint32, etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fsel_s (etiss_uint32, etiss_uint32, etiss_uint32)
static etiss_uint32 fsqrt_s (etiss_uint32, etiss_uint8)
static etiss_uint32 fcmp_s (etiss_uint32, etiss_uint32, etiss_uint32)
static etiss_uint32 fcvt_s (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint64 fcvt_32_64 (etiss_uint32, etiss_uint32, etiss_uint8)
static etiss_uint32 fcvt_64_32 (etiss_uint64, etiss_uint32, etiss_uint8)
static etiss_uint32 unbox_s (etiss_uint64)
static etiss_uint32 fclass_s (etiss_uint32)
static etiss_uint32 fget_flags ()
static etiss_uint64 fadd_d (etiss_uint64, etiss_uint64, etiss_uint8)
static etiss_uint64 fsub_d (etiss_uint64, etiss_uint64, etiss_uint8)
static etiss_uint64 fmul_d (etiss_uint64, etiss_uint64, etiss_uint8)
static etiss_uint64 fdiv_d (etiss_uint64, etiss_uint64, etiss_uint8)
static etiss_uint64 fmadd_d (etiss_uint64, etiss_uint64, etiss_uint64, etiss_uint32, etiss_uint8)
static etiss_uint64 fsel_d (etiss_uint64, etiss_uint64, etiss_uint32)
static etiss_uint64 fsqrt_d (etiss_uint64, etiss_uint8)
static etiss_uint64 fcmp_d (etiss_uint64, etiss_uint64, etiss_uint32)
static etiss_uint64 fcvt_d (etiss_uint64, etiss_uint32, etiss_uint8)
static etiss_uint32 fconv_d2f (etiss_uint64, etiss_uint8)
static etiss_uint64 fconv_f2d (etiss_uint32, etiss_uint8)
static etiss_uint64 unbox_d (etiss_uint64)
static etiss_uint64 fclass_d (etiss_uint64)
static etiss_uint64 etiss_get_cycles (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers)
static etiss_uint64 etiss_get_time ()
static etiss_uint64 etiss_get_instret (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers)
static etiss_uint32 csr_read (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers, etiss_uint32 csr)
static void csr_write (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers, etiss_uint32 csr, etiss_uint32 val)
Function Documentation
csr_read()
static etiss_uint32 csr_read (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers, etiss_uint32 csr) inline static
Definition at line 151 of file RV32IMACFDFuncs.h.
References RV32IMACFD::cpu, RV32IMACFD::CSR, etiss_get_cycles(), etiss_get_instret(), and etiss_get_time().
csr_write()
static void csr_write (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers, etiss_uint32 csr, etiss_uint32 val) inline static
Definition at line 182 of file RV32IMACFDFuncs.h.
References RV32IMACFD::cpu.
etiss_get_cycles()
static etiss_uint64 etiss_get_cycles (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers) inline static
Definition at line 13 of file CSRCounters.cpp.
References ETISS_CPU::cpuCycleTime_ps, and ETISS_CPU::cpuTime_ps.
Referenced by csr_read().
etiss_get_instret()
static etiss_uint64 etiss_get_instret (ETISS_CPU *const cpu, ETISS_System *const system, void *const *const plugin_pointers) inline static
Definition at line 26 of file CSRCounters.cpp.
References ETISS_CPU::cpuCycleTime_ps, and ETISS_CPU::cpuTime_ps.
Referenced by csr_read().
etiss_get_time()
static etiss_uint64 etiss_get_time () inline static
Definition at line 18 of file CSRCounters.cpp.
Referenced by csr_read().
fadd_d()
static etiss_uint64 fadd_d (etiss_uint64 , etiss_uint64 , etiss_uint8) inline static
Definition at line 234 of file fp_functions.cpp.
References nan(), quiet_nan32, and rmm_map.
fadd_s()
static etiss_uint32 fadd_s (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 59 of file fp_functions.cpp.
References rmm_map.
fclass_d()
static etiss_uint64 fclass_d (etiss_uint64) inline static
Definition at line 366 of file fp_functions.cpp.
References sign().
fclass_s()
static etiss_uint32 fclass_s (etiss_uint32) inline static
Definition at line 183 of file fp_functions.cpp.
References sign().
fcmp_d()
static etiss_uint64 fcmp_d (etiss_uint64 , etiss_uint64 , etiss_uint32) inline static
Definition at line 278 of file fp_functions.cpp.
References nan(), and quiet_nan32.
fcmp_s()
static etiss_uint32 fcmp_s (etiss_uint32 , etiss_uint32 , etiss_uint32) inline static
Definition at line 99 of file fp_functions.cpp.
References nan(), and quiet_nan32.
fconv_d2f()
static etiss_uint32 fconv_d2f (etiss_uint64 , etiss_uint8) inline static
Definition at line 212 of file fp_functions.cpp.
References nan(), and rmm_map.
fconv_f2d()
static etiss_uint64 fconv_f2d (etiss_uint32 , etiss_uint8) inline static
Definition at line 223 of file fp_functions.cpp.
References nan(), and rmm_map.
fcvt_32_64()
static etiss_uint64 fcvt_32_64 (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 395 of file fp_functions.cpp.
References rmm_map.
fcvt_64_32()
static etiss_uint32 fcvt_64_32 (etiss_uint64 , etiss_uint32 , etiss_uint8) inline static
Definition at line 414 of file fp_functions.cpp.
References rmm_map.
fcvt_d()
static etiss_uint64 fcvt_d (etiss_uint64 , etiss_uint32 , etiss_uint8) inline static
Definition at line 308 of file fp_functions.cpp.
References rmm_map.
fcvt_s()
static etiss_uint32 fcvt_s (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 129 of file fp_functions.cpp.
References rmm_map.
fdiv_d()
static etiss_uint64 fdiv_d (etiss_uint64 , etiss_uint64 , etiss_uint8) inline static
Definition at line 262 of file fp_functions.cpp.
References rmm_map.
fdiv_s()
static etiss_uint32 fdiv_s (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 83 of file fp_functions.cpp.
References rmm_map.
fget_flags()
static etiss_uint32 fget_flags () inline static
Definition at line 55 of file fp_functions.cpp.
fmadd_d()
static etiss_uint64 fmadd_d (etiss_uint64 , etiss_uint64 , etiss_uint64 , etiss_uint32 , etiss_uint8) inline static
Definition at line 331 of file fp_functions.cpp.
References rmm_map.
fmadd_s()
static etiss_uint32 fmadd_s (etiss_uint32 , etiss_uint32 , etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 152 of file fp_functions.cpp.
References rmm_map.
fmul_d()
static etiss_uint64 fmul_d (etiss_uint64 , etiss_uint64 , etiss_uint8) inline static
Definition at line 254 of file fp_functions.cpp.
References rmm_map.
fmul_s()
static etiss_uint32 fmul_s (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 75 of file fp_functions.cpp.
References rmm_map.
fsel_d()
static etiss_uint64 fsel_d (etiss_uint64 , etiss_uint64 , etiss_uint32) inline static
Definition at line 340 of file fp_functions.cpp.
References max(), and min().
fsel_s()
static etiss_uint32 fsel_s (etiss_uint32 , etiss_uint32 , etiss_uint32) inline static
Definition at line 161 of file fp_functions.cpp.
fsqrt_d()
static etiss_uint64 fsqrt_d (etiss_uint64 , etiss_uint8) inline static
Definition at line 270 of file fp_functions.cpp.
References rmm_map.
fsqrt_s()
static etiss_uint32 fsqrt_s (etiss_uint32 , etiss_uint8) inline static
Definition at line 91 of file fp_functions.cpp.
References rmm_map.
fsub_d()
static etiss_uint64 fsub_d (etiss_uint64 , etiss_uint64 , etiss_uint8) inline static
Definition at line 246 of file fp_functions.cpp.
References rmm_map.
fsub_s()
static etiss_uint32 fsub_s (etiss_uint32 , etiss_uint32 , etiss_uint8) inline static
Definition at line 67 of file fp_functions.cpp.
References rmm_map.
leave()
static void leave (etiss_int32 priv_lvl) inline static
raise()
static void raise (etiss_int32 irq, etiss_int32 mcause) inline static
This file contains the function macros for the RV32IMACFD core architecture.
unbox_d()
static etiss_uint64 unbox_d (etiss_uint64) inline static
unbox_s()
static etiss_uint32 unbox_s (etiss_uint64) inline static
Definition at line 436 of file fp_functions.cpp.
References max(), and v.
wait()
static void wait (etiss_int32 flag) inline static