ETISS 0.8.0: /home/runner/work/etiss_test/etiss_test/JITImpl/TCC/CMakeLists.txt File Reference
/home/runner/work/etiss_test/etiss_test/JITImpl/TCC/CMakeLists.txt File Reference
Functions
set (ETISS_TCC_SELINUX OFF CACHE BOOL "Enable SELinux support in the TCC JIT engine") unset(TCCJIT_ARCH) if(UNIX) set(TCCJIT_ARCH unix) execute_process(COMMAND getenforce OUTPUT_VARIABLE ETISS_TCC_GETENFORCE_OUT OUTPUT_STRIP_TRAILING_WHITESPACE) if(ETISS_TCC_GETENFORCE_OUT STREQUAL "Enforcing") set(ETISS_TCC_SELINUX ON) endif() elseif(WIN32) if(CMAKE_SIZEOF_VOID_P EQUAL 8) set(TCCJIT_ARCH win64) else() set(TCCJIT_ARCH win32) endif() else() message(ERROR "cannot build TCCJIT on this unknown system") endif() set(ETISS_TCC_CONFIGURE_ARGS "") if(ETISS_TCC_SELINUX) set(ETISS_TCC_CONFIGURE_ARGS $
with selinux endif () if(NOT EXISTS $
Function Documentation
endif()
with selinux endif ()
Definition at line 72 of file CMakeLists.txt.
set()
set (ETISS_TCC_SELINUX OFF CACHE BOOL "Enable SELinux support in the TCC JIT engine")
Definition at line 39 of file CMakeLists.txt.
Referenced by etiss::instr::InstructionCollection::addTo(), etiss::instr::InstructionClass::addTo(), etiss::instr::InstructionGroup::addTo(), etiss::Configuration::Configuration(), CPUArch_finalizeInstrSet(), xpath_ast_node::eval_node_set(), etiss::plugin::PrintInstruction::finalizeInstrSet(), etiss::plugin::InstructionSpecificAddressCallback::finalizeInstrSet(), etiss::plugin::gdb::Server::finalizeInstrSet(), etiss::CPUArch::finalizeInstrSet(), get_variable_scratch(), xpath_parser::parse_relative_location_path(), xpath_parser::parse_step(), and Server_finalizeInstrSet().