ETISS 0.8.0: /home/runner/work/etiss_test/etiss_test/ArchImpl/RISCV64/RISCV64Timer.cpp File Reference
RISCV64Timer.cpp File Reference
#include "RISCV64Timer.h"
#include "Encoding.h"
#include "etiss/CPUArch.h"
Functions
static etiss_int32 iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
static etiss_int32 iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static etiss_int32 dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
static void syncTime (void *handle, ETISS_CPU *cpu)
Function Documentation
dbg_read()
static etiss_int32 dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 101 of file RISCV64Timer.cpp.
References ETISS_System::dbg_read, ETISS_System::handle, length(), memcpy(), RISCV64Timer::mtime_, MTIME_ADDR, MTIMECMP_ADDR, etiss::mm::NOERROR, RISCV64TimerSystem::orig, and RISCV64TimerSystem::this_.
Referenced by RISCV64Timer::wrap().
dbg_write()
static etiss_int32 dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 122 of file RISCV64Timer.cpp.
References ETISS_System::dbg_write, ETISS_System::handle, length(), memcpy(), MTIME_ADDR, MTIMECMP_ADDR, RISCV64Timer::mtimecmp_buf_, etiss::mm::NOERROR, RISCV64TimerSystem::orig, and RISCV64TimerSystem::this_.
Referenced by RISCV64Timer::wrap().
dread()
etiss_int32 dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 61 of file RISCV64Timer.cpp.
References ETISS_System::dread, ETISS_System::handle, length(), memcpy(), RISCV64Timer::mtime_, MTIME_ADDR, MTIMECMP_ADDR, etiss::mm::NOERROR, RISCV64TimerSystem::orig, and RISCV64TimerSystem::this_.
Referenced by RISCV64Timer::wrap().
dwrite()
static etiss_int32 dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 82 of file RISCV64Timer.cpp.
References ETISS_System::dwrite, ETISS_System::handle, length(), memcpy(), MTIME_ADDR, MTIMECMP_ADDR, RISCV64Timer::mtimecmp_buf_, etiss::mm::NOERROR, RISCV64TimerSystem::orig, and RISCV64TimerSystem::this_.
Referenced by RISCV64Timer::wrap().
iread()
static etiss_int32 iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length) static
Definition at line 47 of file RISCV64Timer.cpp.
References ETISS_System::handle, ETISS_System::iread, length(), and RISCV64TimerSystem::orig.
Referenced by RISCV64Timer::wrap().
iwrite()
static etiss_int32 iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length) static
Definition at line 54 of file RISCV64Timer.cpp.
References ETISS_System::handle, ETISS_System::iwrite, length(), and RISCV64TimerSystem::orig.
Referenced by RISCV64Timer::wrap().
syncTime()
static void syncTime (void * handle, ETISS_CPU * cpu) static
Definition at line 141 of file RISCV64Timer.cpp.
References ETISS_System::handle, RISCV64TimerSystem::orig, and ETISS_System::syncTime.
Referenced by RISCV64Timer::wrap().