ETISS 0.8.0: xpath_parser Struct Reference
xpath_parser Struct Reference
Classes
struct binary_op_t
Public Member Functions
void throw_error (const char *message)
void throw_error_oom ()
void * alloc_node ()
const char_t * alloc_string (const xpath_lexer_string &value)
xpath_ast_node * parse_function_helper (ast_type_t type0, ast_type_t type1, size_t argc, xpath_ast_node *args[2])
xpath_ast_node * parse_function (const xpath_lexer_string &name, size_t argc, xpath_ast_node *args[2])
axis_t parse_axis_name (const xpath_lexer_string &name, bool &specified)
nodetest_t parse_node_test_type (const xpath_lexer_string &name)
xpath_ast_node * parse_primary_expression ()
xpath_ast_node * parse_filter_expression ()
xpath_ast_node * parse_step (xpath_ast_node *set)
xpath_ast_node * parse_relative_location_path (xpath_ast_node *set)
xpath_ast_node * parse_location_path ()
xpath_ast_node * parse_path_or_unary_expression ()
xpath_ast_node * parse_expression_rec (xpath_ast_node *lhs, int limit)
xpath_ast_node * parse_expression ()
xpath_parser (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
xpath_ast_node * parse ()
Static Public Member Functions
static xpath_ast_node * parse (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
Public Attributes
xpath_allocator * _alloc
xpath_lexer _lexer
const char_t * _query
xpath_variable_set * _variables
xpath_parse_result * _result
char_t _scratch [32]
Detailed Description
Definition at line 9686 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_parser()
xpath_parser::xpath_parser (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) inline
Definition at line 10515 of file pugixml.cpp.
Member Function Documentation
alloc_node()
void* xpath_parser::alloc_node () inline
Definition at line 9723 of file pugixml.cpp.
References _alloc, xpath_allocator::allocate_nothrow(), and throw_error_oom().
Referenced by parse_expression_rec(), parse_filter_expression(), parse_function(), parse_function_helper(), parse_location_path(), parse_path_or_unary_expression(), parse_primary_expression(), parse_relative_location_path(), and parse_step().
alloc_string()
const char_t* xpath_parser::alloc_string (const xpath_lexer_string & value) inline
Definition at line 9733 of file pugixml.cpp.
References _alloc, xpath_allocator::allocate_nothrow(), xpath_lexer_string::begin, c, xpath_lexer_string::end, length(), memcpy(), and throw_error_oom().
Referenced by parse_primary_expression(), and parse_step().
parse() [1/2]
xpath_ast_node* xpath_parser::parse () inline
Definition at line 10520 of file pugixml.cpp.
References _lexer, xpath_lexer::current(), lex_eof, parse_expression(), and throw_error().
parse() [2/2]
static xpath_ast_node* xpath_parser::parse (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) inline static
Definition at line 10533 of file pugixml.cpp.
References get_metrics::parser.
parse_axis_name()
axis_t xpath_parser::parse_axis_name (const xpath_lexer_string & name, bool & specified) inline
Definition at line 9885 of file pugixml.cpp.
References axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_following, axis_following_sibling, axis_namespace, axis_parent, axis_preceding, axis_preceding_sibling, axis_self, name, and PUGIXML_TEXT.
Referenced by parse_step().
parse_expression()
xpath_ast_node* xpath_parser::parse_expression () inline
Definition at line 10513 of file pugixml.cpp.
References parse_expression_rec(), and parse_path_or_unary_expression().
Referenced by parse(), parse_filter_expression(), parse_primary_expression(), and parse_step().
parse_expression_rec()
xpath_ast_node* xpath_parser::parse_expression_rec (xpath_ast_node * lhs, int limit) inline
Definition at line 10464 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_union, ast_unknown, xpath_parser::binary_op_t::asttype, xpath_lexer::next(), xpath_parser::binary_op_t::parse(), parse_path_or_unary_expression(), xpath_parser::binary_op_t::precedence, xpath_ast_node::rettype(), xpath_parser::binary_op_t::rettype, throw_error(), and pugi::xpath_type_node_set.
Referenced by parse_expression(), and parse_path_or_unary_expression().
parse_filter_expression()
xpath_ast_node* xpath_parser::parse_filter_expression () inline
Definition at line 10096 of file pugixml.cpp.
References _lexer, alloc_node(), ast_filter, ast_filter_posinv, xpath_lexer::current(), xpath_ast_node::is_posinv(), lex_close_square_brace, lex_open_square_brace, xpath_lexer::next(), parse_expression(), parse_primary_expression(), xpath_ast_node::rettype(), throw_error(), pugi::xpath_type_node_set, and pugi::xpath_type_number.
Referenced by parse_path_or_unary_expression().
parse_function()
xpath_ast_node* xpath_parser::parse_function (const xpath_lexer_string & name, size_t argc, xpath_ast_node * args[2]) inline
Definition at line 9763 of file pugixml.cpp.
References alloc_node(), get_metrics::args, ast_func_boolean, ast_func_ceiling, ast_func_concat, ast_func_contains, ast_func_count, ast_func_false, ast_func_floor, ast_func_id, ast_func_lang, ast_func_last, ast_func_local_name_0, ast_func_local_name_1, ast_func_name_0, ast_func_name_1, ast_func_namespace_uri_0, ast_func_namespace_uri_1, ast_func_normalize_space_0, ast_func_normalize_space_1, ast_func_not, ast_func_number_0, ast_func_number_1, ast_func_position, ast_func_round, ast_func_starts_with, ast_func_string_0, ast_func_string_1, ast_func_string_length_0, ast_func_string_length_1, ast_func_substring_2, ast_func_substring_3, ast_func_substring_after, ast_func_substring_before, ast_func_sum, ast_func_translate, ast_func_true, name, parse_function_helper(), PUGIXML_TEXT, throw_error(), pugi::xpath_type_boolean, pugi::xpath_type_node_set, pugi::xpath_type_number, and pugi::xpath_type_string.
Referenced by parse_primary_expression().
parse_function_helper()
xpath_ast_node* xpath_parser::parse_function_helper (ast_type_t type0, ast_type_t type1, size_t argc, xpath_ast_node * args[2]) inline
Definition at line 9753 of file pugixml.cpp.
References alloc_node(), get_metrics::args, throw_error(), pugi::xpath_type_node_set, and pugi::xpath_type_string.
Referenced by parse_function().
parse_location_path()
xpath_ast_node* xpath_parser::parse_location_path () inline
Definition at line 10299 of file pugixml.cpp.
References _lexer, alloc_node(), ast_step, ast_step_root, axis_descendant_or_self, xpath_lexer::current(), lex_axis_attribute, lex_dot, lex_double_dot, lex_double_slash, lex_multiply, lex_slash, lex_string, xpath_lexer::next(), nodetest_type_node, parse_relative_location_path(), and pugi::xpath_type_node_set.
Referenced by parse_path_or_unary_expression().
parse_node_test_type()
nodetest_t xpath_parser::parse_node_test_type (const xpath_lexer_string & name) inline
Definition at line 9953 of file pugixml.cpp.
References name, nodetest_none, nodetest_type_comment, nodetest_type_node, nodetest_type_pi, nodetest_type_text, and PUGIXML_TEXT.
Referenced by parse_path_or_unary_expression(), and parse_step().
parse_path_or_unary_expression()
xpath_ast_node* xpath_parser::parse_path_or_unary_expression () inline
Definition at line 10337 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_negate, ast_step, axis_descendant_or_self, xpath_lexer::contents(), ct_space, xpath_lexer::current(), lex_double_slash, lex_minus, lex_number, lex_open_brace, lex_quoted_string, lex_slash, lex_string, lex_var_ref, xpath_lexer::next(), nodetest_none, nodetest_type_node, parse_expression_rec(), parse_filter_expression(), parse_location_path(), parse_node_test_type(), parse_relative_location_path(), PUGI__IS_CHARTYPE, xpath_ast_node::rettype(), xpath_lexer::state(), throw_error(), pugi::xpath_type_node_set, and pugi::xpath_type_number.
Referenced by parse_expression(), and parse_expression_rec().
parse_primary_expression()
xpath_ast_node* xpath_parser::parse_primary_expression () inline
Definition at line 9989 of file pugixml.cpp.
References _lexer, _scratch, _variables, alloc_node(), alloc_string(), get_metrics::args, ast_number_constant, ast_string_constant, ast_variable, xpath_lexer_string::begin, xpath_lexer::contents(), convert_string_to_number_scratch(), xpath_lexer::current(), xpath_lexer_string::end, get_variable_scratch(), lex_close_brace, lex_comma, lex_number, lex_open_brace, lex_quoted_string, lex_string, lex_var_ref, name, xpath_lexer::next(), parse_expression(), parse_function(), xpath_ast_node::set_next(), throw_error(), throw_error_oom(), pugi::xpath_type_number, and pugi::xpath_type_string.
Referenced by parse_filter_expression().
parse_relative_location_path()
xpath_ast_node* xpath_parser::parse_relative_location_path (xpath_ast_node * set) inline
Definition at line 10279 of file pugixml.cpp.
References _lexer, alloc_node(), ast_step, axis_descendant_or_self, xpath_lexer::current(), lex_double_slash, lex_slash, xpath_lexer::next(), nodetest_type_node, parse_step(), and set().
Referenced by parse_location_path(), and parse_path_or_unary_expression().
parse_step()
xpath_ast_node* xpath_parser::parse_step (xpath_ast_node * set) inline
Definition at line 10128 of file pugixml.cpp.
References _lexer, alloc_node(), alloc_string(), ast_predicate, ast_step, axis_attribute, axis_child, axis_parent, axis_self, xpath_lexer_string::begin, xpath_lexer::contents(), xpath_lexer::current(), xpath_lexer_string::end, lex_axis_attribute, lex_close_brace, lex_close_square_brace, lex_dot, lex_double_colon, lex_double_dot, lex_multiply, lex_open_brace, lex_open_square_brace, lex_quoted_string, lex_string, xpath_lexer::next(), nodetest_all, nodetest_all_in_namespace, nodetest_name, nodetest_none, nodetest_pi, nodetest_type_node, parse_axis_name(), parse_expression(), parse_node_test_type(), PUGIXML_TEXT, set(), xpath_ast_node::set_next(), xpath_ast_node::set_right(), throw_error(), and pugi::xpath_type_node_set.
Referenced by parse_relative_location_path().
throw_error()
void xpath_parser::throw_error (const char * message) inline
Definition at line 9702 of file pugixml.cpp.
References _lexer, _query, _result, and xpath_lexer::current_pos().
Referenced by parse(), parse_expression_rec(), parse_filter_expression(), parse_function(), parse_function_helper(), parse_path_or_unary_expression(), parse_primary_expression(), parse_step(), and throw_error_oom().
throw_error_oom()
void xpath_parser::throw_error_oom () inline
Definition at line 9714 of file pugixml.cpp.
References throw_error().
Referenced by alloc_node(), alloc_string(), and parse_primary_expression().
Member Data Documentation
_alloc
xpath_allocator* xpath_parser::_alloc
Definition at line 9688 of file pugixml.cpp.
Referenced by alloc_node(), and alloc_string().
_lexer
xpath_lexer xpath_parser::_lexer
Definition at line 9689 of file pugixml.cpp.
Referenced by parse(), parse_expression_rec(), parse_filter_expression(), parse_location_path(), parse_path_or_unary_expression(), parse_primary_expression(), parse_relative_location_path(), parse_step(), and throw_error().
_query
const char_t* xpath_parser::_query
Definition at line 9691 of file pugixml.cpp.
Referenced by throw_error().
_result
xpath_parse_result* xpath_parser::_result
Definition at line 9694 of file pugixml.cpp.
Referenced by throw_error().
_scratch
char_t xpath_parser::_scratch[32]
Definition at line 9696 of file pugixml.cpp.
Referenced by parse_primary_expression().
_variables
xpath_variable_set* xpath_parser::_variables
Definition at line 9692 of file pugixml.cpp.
Referenced by parse_primary_expression().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss_test/etiss_test/src/fault/xml/pugixml.cpp